import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Swatrix IT Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-light text-dark">{children}</body>
    </html>
  )
}
